services:
  bradroot-site:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - /app/scripts/node_modules
      - ~/.ssh:/root/.ssh:ro
    environment:
      - GIT_AUTHOR_NAME=Brad Root
      - GIT_AUTHOR_EMAIL=bradroot@me.com
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped
